filebeat.inputs:
  - type: filestream
    id: kirana-logs
    enabled: true
    paths:
      - /usr/share/filebeat/logs/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"
